// 11.React/my-react-app/src/about.js
import { useEffect, useState } from "react";

export function AboutComponent(){
    const [isColorRed, setIsColorRed] = useState(false);

    function changeColor(){
        setIsColorRed((prev)=> !prev);
    }

    function showButton(){
        if(isColorRed){
            return (<button style={{backgroundColor: "red", color:"white"}}>Kırmızı</button>)
        }else{
            return (<button style={{backgroundColor: "blue", color:"white"}}>Mavi</button>)
        }
    }

    return(
        <>
        <h1>About page</h1>
        <button onClick={changeColor}>Rengi Değiştir</button>
        <br />
        {showButton()}
        </>
    )
}

// 12.Angular/my-first-app/src/app/about/about.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [],
  template:`
  <h1>About Page</h1>
  <button (click)="changeColor()">Rengi Değiştir</button>
  <br>
  @if(isColorRed){
    <button style="background-color: red; color:white">Kırmızı</button>
  }@else {
    <button style="background-color: blue; color:white">Mavi</button>
  } 
  `
})
export class AboutComponent {
  isColorRed: boolean = false;

  changeColor(){
    this.isColorRed = !this.isColorRed;
  }
}
